basePath: /v1
definitions:
  handler.NewOrderRequest:
    properties:
      items:
        items:
          $ref: '#/definitions/handler.OrderItemRequest'
        type: array
    required:
    - items
    type: object
  handler.OrderItemRequest:
    properties:
      price:
        type: number
      productId:
        type: integer
      quantity:
        type: integer
    required:
    - price
    - productId
    - quantity
    type: object
  handler.ResponseOrder:
    properties:
      createdAt:
        type: string
      id:
        type: integer
      items:
        items:
          $ref: '#/definitions/handler.ResponseOrderItem'
        type: array
      status:
        type: string
      totalAmount:
        type: number
      updatedAt:
        type: string
      userId:
        type: integer
    type: object
  handler.ResponseOrderItem:
    properties:
      id:
        type: integer
      price:
        type: number
      productId:
        type: integer
      quantity:
        type: integer
      subtotal:
        type: number
    type: object
  handler.UpdateStatusRequest:
    properties:
      status:
        type: string
    required:
    - status
    type: object
host: localhost:9090
info:
  contact: {}
  description: Order management microservice
  title: Order Service API
  version: 1.0.0
paths:
  /order/:
    get:
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handler.ResponseOrder'
            type: array
      security:
      - BearerAuth: []
      summary: Get all orders
      tags:
      - Order
    post:
      parameters:
      - description: Order
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.NewOrderRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.ResponseOrder'
      security:
      - BearerAuth: []
      summary: Create order
      tags:
      - Order
  /order/{id}:
    get:
      parameters:
      - description: Order ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.ResponseOrder'
      security:
      - BearerAuth: []
      summary: Get order by ID
      tags:
      - Order
  /order/{id}/status:
    put:
      parameters:
      - description: Order ID
        in: path
        name: id
        required: true
        type: integer
      - description: Status
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.UpdateStatusRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.ResponseOrder'
      security:
      - BearerAuth: []
      summary: Update order status
      tags:
      - Order
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
